[package]
name = "hyper-proxy"
version = "0.4.0"
authors = ["Johann Tuffe <tafia973@gmail.com"]
description = "A proxy connector for Hyper-based applications"

documentation = "https://docs.rs/hyper-proxy"
repository = "https://github.com/tafia/hyper-proxy"

readme = "README.md"
keywords = ["hyper", "proxy", "tokio", "ssl"]
categories = ["web-programming::http-client", "asynchronous", "authentication"]
license = "MIT"

[dependencies]
hyper = "0.11.0"
futures = "0.1.17"
tokio-core = "0.1.10"
tokio-io = "0.1.4"
bytes = "0.4.5"
tokio-tls = "0.1.3"
hyper-tls = "0.1.2"
native-tls = "0.1.4"
