[package]
name = "hyper-proxy"
version = "0.1.0"
authors = ["Johann Tuffe"]

[dependencies]
hyper = "0.11.0"
futures = "0.1.17"
tokio-core = "0.1.10"
tokio-io = "0.1.4"
bytes = "0.4.5"
tokio-tls = "0.1.3"
hyper-tls = "0.1.2"
native-tls = "0.1.4"
